### ISSUE TITLE
Milestone: Combine vision with text to visually automate desktop using words

### ISSUE THREAD

**Issue by ZacTolle** [ZacTolle/modelprompter#40]
## Milestones
- [ ] Allow ModelPrompter to output code that automates the desktop with [nut.js](https://nut-tree.github.io/apidoc/)
- [ ] Before each major step, take a screenshot of the desktop and segment it to know what to click on or what to do
- [ ] Recursively step through goals and retake images as needed

## Extras
- [ ] Voice to text
- [ ] Text to speech
